In [1]:
#implementing a simple linear regression model for salary of employees with number of years of experience 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
dataset=pd.read_csv('Salary_Data.csv')

In [3]:
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
x=dataset.iloc[:,:-1].values

In [5]:
x

array([[  1.1],
       [  1.3],
       [  1.5],
       [  2. ],
       [  2.2],
       [  2.9],
       [  3. ],
       [  3.2],
       [  3.2],
       [  3.7],
       [  3.9],
       [  4. ],
       [  4. ],
       [  4.1],
       [  4.5],
       [  4.9],
       [  5.1],
       [  5.3],
       [  5.9],
       [  6. ],
       [  6.8],
       [  7.1],
       [  7.9],
       [  8.2],
       [  8.7],
       [  9. ],
       [  9.5],
       [  9.6],
       [ 10.3],
       [ 10.5]])

In [6]:
y=dataset.iloc[:,-1].values

In [7]:
y

array([  39343.,   46205.,   37731.,   43525.,   39891.,   56642.,
         60150.,   54445.,   64445.,   57189.,   63218.,   55794.,
         56957.,   57081.,   61111.,   67938.,   66029.,   83088.,
         81363.,   93940.,   91738.,   98273.,  101302.,  113812.,
        109431.,  105582.,  116969.,  112635.,  122391.,  121872.])

In [8]:
#splitting data into train and test set
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=1/3, random_state=0)

/home/gaurav/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
x_train

array([[  2.9],
       [  5.1],
       [  3.2],
       [  4.5],
       [  8.2],
       [  6.8],
       [  1.3],
       [ 10.5],
       [  3. ],
       [  2.2],
       [  5.9],
       [  6. ],
       [  3.7],
       [  3.2],
       [  9. ],
       [  2. ],
       [  1.1],
       [  7.1],
       [  4.9],
       [  4. ]])

In [10]:
y_train


array([  56642.,   66029.,   64445.,   61111.,  113812.,   91738.,
         46205.,  121872.,   60150.,   39891.,   81363.,   93940.,
         57189.,   54445.,  105582.,   43525.,   39343.,   98273.,
         67938.,   56957.])

In [11]:
x_test

array([[  1.5],
       [ 10.3],
       [  4.1],
       [  3.9],
       [  9.5],
       [  8.7],
       [  9.6],
       [  4. ],
       [  5.3],
       [  7.9]])

In [12]:
y_test

array([  37731.,  122391.,   57081.,   63218.,  116969.,  109431.,
        112635.,   55794.,   83088.,  101302.])

In [13]:
#fitting training set to the linear model
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
y_pred=regressor.predict(x_test)

In [15]:
y_pred

array([  40835.10590871,  123079.39940819,   65134.55626083,
         63265.36777221,  115602.64545369,  108125.8914992 ,
        116537.23969801,   64199.96201652,   76349.68719258,
        100649.1375447 ])

In [18]:
regressor.score(x_test,y_test)

0.97491544077083525

In [ ]:
#plotting the scatter plot for training set
plt.scatter(x_train,y_train, color='blue')
plt.plot(x_train,regressor.predict(x_train),color='red')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.title('salary vs experience(training set)')
plt.show()

In [ ]:
#plotting the scatter plot for training set
plt.scatter(x_test,y_test, color='blue')
plt.plot(x_train,regressor.predict(x_train),color='red')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.title('salary vs experience(test set)')
plt.show()